####################################################################################################
################ Config file for plotting ##########################################################
####################################################################################################


############################### Input for plotting ##################################################
### bin_width to bin the data
### change_time: from MET to seconds since midnight
### show grb trigger times? if yes at which time ('20:57:03.000' format) and what name?
### xlim and ylim (as tuple e.g. [0,100])
### legend outside of the plot?
### dpi of plot
### mpl_style: path to custom style file
###
### Optional Highlight config:
### highlight:
###    grb_trigger:  null
###    occ_region:   null
### 
#####################################################################################################


plot:
  bin_width:            5
  time_since_midnight:  true
  time_format:          'h'
  time_t0:              null
  set_axis_limits:      false
  xlim:                 null
  ylim:                 null
  residual_ylim:        null
  xlabel:               null
  ylabel:               null
  dpi:                  600
  show_legend:          true
  legend_outside:       false
  show_title:           true
  axis_title:           null


component:
  show_data:            true
  show_model:           true
  show_residuals:       true
  show_ppc:             true

  show_all_sources:     true
  show_earth:           true
  show_cgb:             true
  show_sun:             true
  show_saa:             true
  show_cr:              true
  show_constant:        true
  show_crab:            true

  show_occ_region:      false
  show_grb_trigger:     false


style:
    mpl_style:    null # 'aa.mplstyle'

    model:
      color:      'red'
      alpha:      .8
      linewidth:  0.6
      show_label: true

    data:
      color: 'k'
      alpha: .6
      linewidth: 0.18
      marker_size: 1
      elinewidth: 0.2
      show_label: true
      rasterized': false

    sources:
        cr:
          color: [0.267004, 0.004874, 0.329415]
          alpha: .6
          linewidth: 0.8
          show_label: true

        earth:
          color: [0.267968, 0.223549, 0.512008]
          alpha: .6
          linewidth: 0.8
          show_label: true

        cgb:
          color: [0.190631, 0.407061, 0.556089]
          alpha: .6
          linewidth: 0.8
          show_label: true

        constant:
          color: [0.127568, 0.566949, 0.550556]
          alpha: .6
          linewidth: 0.8
          show_label: true

        saa:
          color: [0.20803,  0.718701, 0.472873]
          alpha: .6
          linewidth: 0.8
          show_label: true

        crab:
          color: [0.565498, 0.84243,  0.262877]
          alpha: .6
          linewidth: 0.8
          show_label: true
        sun:
          color: [0.993248, 0.906157, 0.143936]
          alpha: .6
          linewidth: 0.8
          show_label: true

        default:
          color: 'blue'
          alpha: .6
          linewidth: 0.8
          show_label: true

        global:
          cmap:  'viridis'
          alpha: .6
          linewidth: 0.8
          show_label: true

        use_global: false

    ppc:
      color: ['lightgreen', 'green', 'darkgreen']
      alpha: 0.6

    legend_kwargs:
        # loc: 'center left'
        # bbox_to_anchor: [-0.17, -0.5]
        ncol: 3


highlight:
    # grb_trigger:
    #   - name: 'GRB 150126 - KONUS-WIND Trigger'
    #     trigger_time: '2015-01-26T20:51:43.524'
    #     time_format: 'UTC'
    #     time_offset: 0.
    #     color: 'b'
    #     linestyle: '-'
    #     linewidth: 0.8

    # occ_region:
    #   - name: 'Earth occultation'
    #     time_start: '2015-01-26T00:00:00.000'
    #     time_stop: '2015-01-26T20:50:00.000'
    #     time_format: 'UTC'
    #     color: 'grey'
